---
- name: Install epel yum repository
  yum: name="http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm"

- name: Install packages needed to compile PHP 7
  yum: name={{ item }} state=latest
  with_items:
    - autoconf
    - bison
    - aspell-devel
    - bzip2-devel
    - gd-devel
    - gmp-devel
    - libcurl-devel
    - libmcrypt-devel
    - libxml2-devel
    - mysql-devel
    - openssl-devel
    - readline-devel
    - recode-devel
    - t1lib-devel

- name: Clone php7 source
  git: repo=https://git.php.net/repository/php-src.git dest=/home/vagrant/php-src depth=1

- name: Run buildconf
  shell: ./buildconf
  args:
    chdir: /home/vagrant/php-src

- name: Configure the build.
  shell: ./configure {{ php7_configure_string }}
  args:
    chdir: /home/vagrant/php-src

- name: Configure the cli build.
  shell: ./configure {{ php7_cli_configure_string }}
  args:
    chdir: /home/vagrant/php-src

- name: Build PHP7
  shell: make
  args:
    chdir: /home/vagrant/php-src

- name: Install PHP7
  shell: make install
  args:
    chdir: /home/vagrant/php-src
