---
- name: Install dependencies
  yum: pkg={{item}} state=present
  with_items:
    - libffi-devel
    - zlib-devel
    - openssl-devel

- name: Install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest={{ rbenv_root }}

- name: Install ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest={{ rbenv_root }}/plugins/ruby-build

- name: create rbenv group
  group: name=rbenv state=present

- name: add user to rbenv group
  user: name=centos append=yes groups=rbenv
  register: add_group

- name: create shims dir
  file: path={{ rbenv_root }}/shims state=directory

- name: create versions dir
  file: path={{ rbenv_root }}/versions state=directory

- name: Set rbenv env file
  copy: src=rbenv.sh dest=/etc/profile.d mode=0775

- name: Install ruby with rbenv
  shell: bash -lc "CONFIGURE_OPTS="--disable-install-rdoc" rbenv install {{ ruby_version }}"

- name: "set ruby {{ ruby_version }} for system"
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"
