---
- name: Install epel yum repository
  yum: name="http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm"

- name: Install remi yum repository
  yum: name="http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"

- name: Install PHP 5.6
  yum: name={{ item }} state=present enablerepo=remi-php56
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-dbg
    - php-pdo
    - php-fpm
    - php-mbstring
    - php-mcrypt
    - php-mysql
    - php-opcache
    - php-xml
    - php-pecl-xdebug

- name: Start and Enable php-fpm
  service: name=php-fpm state=started enabled=yes

- name: Copy custom php-fpm.conf
  copy: src=php-fpm/zz-app.conf dest=/etc/php-fpm.d/zz-app.conf

- name: Install phpunit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555
